# Generated by Django 5.1.2 on 2024-10-24 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mpesa_express', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='mpesa_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
